version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: proxy_py_db
    restart: always
    environment:
      - POSTGRES_USER=proxy_py
      - POSTGRES_PASSWORD=proxy_py
      - POSTGRES_DB=proxy_py
    volumes:
      - db_data:/var/lib/postgresql/data
  core:
    image: proxy_py
    build: .
    container_name: proxy_py
    command: ./run.sh
    restart: always
    ports:
      - "0.0.0.0:55555:55555"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
